### ISSUE TITLE
Fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by mingodad** [kyx0r/pikevm#1]
When trying to test on Ubuntu 18.04:
```
./test.sh
tr: missing operand after ‘\\n’
Two strings must be given when translating.
Try 'tr --help' for more information.
```

**Comment by kyx0r** [comment]
Hello,
This is likely due to echo not being portable, try the last commit on master now. Is it fixed?

**Comment by mingodad** [comment]
Thanks for the fast reply !
But it seems that we need to move the compilation line before the tests:
```
./test.sh
./test.sh: 474: ./test.sh: ./a.out: not found
fail test1 regex:abc input:abcdef expect:(0,3) output:\
```
See this diff:
```
diff -u test.sh test-da.sh 
--- test.sh	2021-11-10 16:37:02.784629571 +0100
+++ test-da.sh	2021-11-10 16:38:18.638612095 +0100
@@ -467,6 +467,8 @@
 (0,0)
 "
 
+gcc pike.c -pedantic -Wall -Wfatal-errors -std=c99 $CFLAGS
+
 c=1
 printf '%s\n' "$regex" | while read re; do
 	inp=$(printf '%s\n' "$input" | awk -v c=$c 'BEGIN{ RS = "" ; FS = "\n" }{print $c}')
@@ -485,4 +487,3 @@
 	c=$((c+1))
 done
 
-gcc pike.c -pedantic -Wall -Wfatal-errors -std=c99 $CFLAGS
```

**Comment by kyx0r** [comment]
Yeah, I agree that's a minor issue. I suppose that developers will prefer the compiler output to be
printed after the test run rather than before, so that you don't have to scroll back 100's of lines to
the possible warning or whatever else. The correct solution to this is to use an if statement and check
for the file. Try last commit, this should work fine. Thanks for the issue.
